In [1]:
from tensorflow.keras.layers import Input, AveragePooling2D
from tensorflow.keras import Model
import numpy as np

In [2]:
inputs = Input(shape=(5,5,3))
x = AveragePooling2D(pool_size=2)(inputs)
model = Model(inputs, x)

In [3]:
model.summary()

Model: "functional"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ input_layer (InputLayer)        │ (None, 5, 5, 3)        │             0 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ average_pooling2d               │ (None, 2, 2, 3)        │             0 │
│ (AveragePooling2D)              │                        │               │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 0 (0.00 B)

 Trainable params: 0 (0.00 B)

 Non-trainable params: 0 (0.00 B)

In [4]:
X = np.random.rand(1,5,5,3)
X

array([[[[0.71738082, 0.87756149, 0.20696107],
         [0.62764078, 0.69174671, 0.92248836],
         [0.10427136, 0.55271254, 0.95691944],
         [0.98999846, 0.63016356, 0.96235608],
         [0.43223266, 0.60301808, 0.49957911]],

        [[0.58809977, 0.9043907 , 0.59509472],
         [0.2495966 , 0.71401479, 0.15879763],
         [0.48443293, 0.67418437, 0.49632231],
         [0.36386556, 0.11045104, 0.46169089],
         [0.99905022, 0.71873674, 0.67495835]],

        [[0.50315476, 0.28462675, 0.42285321],
         [0.35923502, 0.23345807, 0.72668077],
         [0.78429627, 0.82358729, 0.17506168],
         [0.68282424, 0.16793607, 0.0206915 ],
         [0.73326809, 0.43986452, 0.08661036]],

        [[0.92046954, 0.16747567, 0.19866793],
         [0.5929947 , 0.21544885, 0.44881554],
         [0.64017599, 0.20734532, 0.20709383],
         [0.37995743, 0.72054094, 0.19731578],
         [0.94525635, 0.54206609, 0.29708953]],

        [[0.67899938, 0.39615054, 0.43838793],
     

In [5]:
y = model.predict(X)
y

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 37ms/step


array([[[[0.5456795 , 0.79692847, 0.47083542],
         [0.48564208, 0.49187785, 0.7193222 ]],

        [[0.5939635 , 0.22525233, 0.44925433],
         [0.6218135 , 0.47985244, 0.15004069]]]], dtype=float32)

In [6]:
in_json = {
    "in": (X[0]*1000).round().astype(int).astype(str).tolist()
}

In [7]:
out_json = {
    "out": (y[0]*1000000).round().astype(int).astype(str).tolist()
}

In [8]:
import json

In [9]:
with open("averagePooling2D_input.json", "w") as f:
    json.dump(in_json, f, indent=4)

In [10]:
with open("averagePooling2D_output.json", "w") as f:
    json.dump(out_json, f, indent=4)

In [11]:
inputs = Input(shape=(10,10,3))
x = AveragePooling2D(pool_size=3, strides=2)(inputs)
model = Model(inputs, x)

In [12]:
model.summary()

Model: "functional_1"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ input_layer_1 (InputLayer)      │ (None, 10, 10, 3)      │             0 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ average_pooling2d_1             │ (None, 4, 4, 3)        │             0 │
│ (AveragePooling2D)              │                        │               │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 0 (0.00 B)

 Trainable params: 0 (0.00 B)

 Non-trainable params: 0 (0.00 B)

In [13]:
X = np.random.rand(1,10,10,3)
X

array([[[[0.92703129, 0.50597547, 0.7870315 ],
         [0.20679286, 0.90474034, 0.11745805],
         [0.40282497, 0.26109873, 0.32666129],
         [0.790886  , 0.22264575, 0.51160493],
         [0.99190534, 0.08551896, 0.62589324],
         [0.05867718, 0.73004675, 0.58965267],
         [0.90127918, 0.37844153, 0.22278308],
         [0.13123411, 0.43137729, 0.32786433],
         [0.93217009, 0.12426966, 0.88539915],
         [0.94035531, 0.21991742, 0.81905566]],

        [[0.10416797, 0.53036095, 0.20829356],
         [0.34366566, 0.34225222, 0.29139622],
         [0.4218152 , 0.60018077, 0.60164409],
         [0.69218141, 0.51465923, 0.92494721],
         [0.47304769, 0.20024788, 0.51030943],
         [0.43388281, 0.62978969, 0.74495729],
         [0.26505349, 0.95290377, 0.42000776],
         [0.30602809, 0.37475723, 0.87774155],
         [0.45436042, 0.87446879, 0.75843321],
         [0.66656818, 0.49394994, 0.57875128]],

        [[0.78083223, 0.68880745, 0.6938833 ],
         

In [14]:
y = model.predict(X)
y

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 16ms/step


array([[[[0.46363416, 0.52901405, 0.43414015],
         [0.5911941 , 0.39191693, 0.525502  ],
         [0.5777002 , 0.5870075 , 0.49719578],
         [0.49933898, 0.5339971 , 0.5016686 ]],

        [[0.62864494, 0.5215888 , 0.48493636],
         [0.45037037, 0.53586507, 0.51191795],
         [0.5142606 , 0.61012435, 0.5005249 ],
         [0.60387665, 0.53870356, 0.48468664]],

        [[0.6385474 , 0.33872223, 0.48678955],
         [0.40960756, 0.5859695 , 0.5895293 ],
         [0.5085524 , 0.520605  , 0.4697051 ],
         [0.563226  , 0.5246179 , 0.41492033]],

        [[0.59905744, 0.56755203, 0.42166328],
         [0.44616428, 0.50115997, 0.5802784 ],
         [0.5191411 , 0.5358895 , 0.39673316],
         [0.6168883 , 0.5554462 , 0.4298889 ]]]], dtype=float32)

In [15]:
in_json = {
    "in": (X[0]*1000).round().astype(int).astype(str).tolist()
}

In [16]:
out_json = {
    "out": (y[0]*1000000).round().astype(int).astype(str).tolist()
}

In [17]:
with open("averagePooling2D_stride_input.json", "w") as f:
    json.dump(in_json, f, indent=4)

In [18]:
with open("averagePooling2D_stride_output.json", "w") as f:
    json.dump(out_json, f, indent=4)