In [1]:
from tensorflow.keras.layers import Input, BatchNormalization, Dense, Flatten
from tensorflow.keras import Model
import numpy as np

In [2]:
inputs = Input(shape=(5,5,3))
out = BatchNormalization()(inputs)
out = Flatten()(out)
out = Dense(1)(out)
model = Model(inputs, out)

In [3]:
model.summary()

Model: "functional"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ input_layer (InputLayer)        │ (None, 5, 5, 3)        │             0 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ batch_normalization             │ (None, 5, 5, 3)        │            12 │
│ (BatchNormalization)            │                        │               │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ flatten (Flatten)               │ (None, 75)             │             0 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense (Dense)                   │ (None, 1)              │            76 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 88 (352.00 B)

 Trainable params: 82 (328.00 B)

 Non-trainable params: 6 (24.00 B)

In [4]:
X_train = np.random.rand(100,5,5,3)
X_train

array([[[[0.20538619, 0.7611217 , 0.48028893],
         [0.57289602, 0.60081144, 0.52642062],
         [0.82991601, 0.52043189, 0.46599433],
         [0.218208  , 0.03700048, 0.46804102],
         [0.1134269 , 0.76619146, 0.08603748]],

        [[0.93759517, 0.86403508, 0.72652655],
         [0.70846444, 0.78656109, 0.1068495 ],
         [0.76431384, 0.72950923, 0.55485752],
         [0.09650218, 0.40508184, 0.95150425],
         [0.91619699, 0.05037141, 0.98855137]],

        [[0.84589627, 0.33664126, 0.62438261],
         [0.27008007, 0.53272932, 0.20745323],
         [0.95016958, 0.23735849, 0.90814037],
         [0.58579276, 0.91551811, 0.9351074 ],
         [0.53296819, 0.20131612, 0.65120914]],

        [[0.54659155, 0.41902516, 0.7059668 ],
         [0.56152486, 0.89617051, 0.53151901],
         [0.25369086, 0.82125897, 0.74435894],
         [0.38734345, 0.44157449, 0.27752797],
         [0.9626824 , 0.24955077, 0.89733137]],

        [[0.0279756 , 0.29150671, 0.51464606],
     

In [5]:
y_train = np.random.rand(100,1)
y_train

array([[0.96524947],
       [0.40347659],
       [0.01739261],
       [0.23597932],
       [0.0238418 ],
       [0.4944914 ],
       [0.12919981],
       [0.72459414],
       [0.57140798],
       [0.38641192],
       [0.38616971],
       [0.11292659],
       [0.53576623],
       [0.10908928],
       [0.47203529],
       [0.33967134],
       [0.39765632],
       [0.13254829],
       [0.48192292],
       [0.4834302 ],
       [0.16986427],
       [0.3062218 ],
       [0.62335613],
       [0.60246801],
       [0.3241892 ],
       [0.34497433],
       [0.36880441],
       [0.3488615 ],
       [0.68297575],
       [0.13552353],
       [0.59911962],
       [0.56980462],
       [0.24588577],
       [0.19788484],
       [0.22105095],
       [0.64502235],
       [0.72319598],
       [0.24698173],
       [0.53698047],
       [0.63219624],
       [0.98616886],
       [0.66606914],
       [0.16190129],
       [0.48041986],
       [0.96262898],
       [0.12335008],
       [0.9446989 ],
       [0.750

In [6]:
model.compile("adam", "mse")
model.fit(X_train, y_train, epochs=10)

Epoch 1/10
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 1.8422  
Epoch 2/10
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 1.8147
Epoch 3/10
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 1.7030
Epoch 4/10
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 1.6592
Epoch 5/10
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 1.5806
Epoch 6/10
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 1.5520
Epoch 7/10
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 1.5025
Epoch 8/10
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 1.4410
Epoch 9/10
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 1.3792
Epoch 10/10
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 1.3445


In [7]:
model.layers[1].weights

[<Variable path=batch_normalization/gamma, shape=(3,), dtype=float32, value=[0.9649134  0.965995   0.96903545]>,
 <Variable path=batch_normalization/beta, shape=(3,), dtype=float32, value=[ 0.02819148  0.02822662 -0.0283645 ]>,
 <Variable path=batch_normalization/moving_mean, shape=(3,), dtype=float32, value=[0.16649415 0.16428466 0.16471748]>,
 <Variable path=batch_normalization/moving_variance, shape=(3,), dtype=float32, value=[0.69657636 0.6970183  0.6959998 ]>]

In [8]:
X = np.random.rand(1,5,5,3)
X

array([[[[0.31665572, 0.43950441, 0.65549298],
         [0.84676626, 0.16572574, 0.68151462],
         [0.93230743, 0.8834265 , 0.97827671],
         [0.24238576, 0.30127497, 0.50967681],
         [0.64421205, 0.37446094, 0.32594515]],

        [[0.14402464, 0.92592289, 0.05007417],
         [0.92258442, 0.00821299, 0.21664579],
         [0.62039276, 0.97744588, 0.08168193],
         [0.81472812, 0.91750804, 0.53100617],
         [0.11430232, 0.04556226, 0.24420875]],

        [[0.31562347, 0.10173635, 0.05634449],
         [0.8520449 , 0.02009114, 0.95929892],
         [0.86192614, 0.14130254, 0.88339481],
         [0.46407096, 0.67250814, 0.15257626],
         [0.1428145 , 0.07565368, 0.17530209]],

        [[0.97775685, 0.61067272, 0.80623078],
         [0.35791434, 0.81430926, 0.815033  ],
         [0.62679939, 0.85284572, 0.04882388],
         [0.86165372, 0.79805266, 0.82724202],
         [0.92034413, 0.35331138, 0.27999816]],

        [[0.31997461, 0.17562015, 0.68413053],
     

In [9]:
new_model = Model(inputs, model.layers[1].output)
y = new_model.predict(X)
y

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 20ms/step


array([[[[ 2.0167226e-01,  3.4644195e-01,  5.4128301e-01],
         [ 8.1410575e-01,  2.9892817e-02,  5.7148659e-01],
         [ 9.1293085e-01,  8.5971475e-01,  9.1594100e-01],
         [ 1.1586860e-01,  1.8661794e-01,  3.7203291e-01],
         [ 5.8009613e-01,  2.7123719e-01,  1.5877393e-01]],

        [[ 2.2325963e-03,  9.0885007e-01, -1.6143203e-01],
         [ 9.0169799e-01, -1.5222700e-01,  3.1909168e-02],
         [ 5.5257773e-01,  9.6842217e-01, -1.2474461e-01],
         [ 7.7709234e-01,  8.9912057e-01,  3.9679006e-01],
         [-3.2105416e-02, -1.0904293e-01,  6.3901752e-02]],

        [[ 2.0047969e-01, -4.4093169e-02, -1.5415400e-01],
         [ 8.2020414e-01, -1.3849322e-01,  8.9391327e-01],
         [ 8.3161986e-01,  1.6541630e-03,  8.0581081e-01],
         [ 3.7198022e-01,  6.1584616e-01, -4.2456910e-02],
         [ 8.3453953e-04, -7.4250534e-02, -1.6078845e-02]],

        [[ 9.6543837e-01,  5.4435062e-01,  7.1624577e-01],
         [ 2.4933809e-01,  7.7979982e-01,  7.26462

In [10]:
gamma = model.layers[1].weights[0].numpy()
beta = model.layers[1].weights[1].numpy()
moving_mean = model.layers[1].weights[2].numpy()
moving_var = model.layers[1].weights[3].numpy()
epsilon = model.layers[1].epsilon

In [11]:
a = gamma/(moving_var+epsilon)**.5
b = beta-gamma*moving_mean/(moving_var+epsilon)**.5

In [12]:
y-(gamma*(X-moving_mean)/((moving_var+epsilon)**.5)+beta)

array([[[[ 3.20334136e-08,  2.94787872e-08,  2.61280741e-09],
         [ 7.85178740e-08, -1.31062410e-08,  3.07179433e-08],
         [-1.64342250e-08,  4.58670858e-08,  3.43876836e-08],
         [ 2.19613054e-09,  1.98323185e-08,  3.74934843e-08],
         [ 8.42206309e-08, -1.44759799e-09,  2.66302880e-08]],

        [[-1.98688080e-09,  8.87984919e-08, -9.17446435e-09],
         [ 6.34634946e-08, -1.99583728e-08,  1.39736544e-08],
         [-2.80745214e-08,  1.33323888e-07, -7.78392031e-10],
         [ 1.26147767e-07,  2.48037377e-08,  1.93401656e-09],
         [-4.39780466e-09, -1.32155878e-08,  1.97457270e-08]],

        [[ 1.54786609e-08, -1.19851679e-08, -2.49014157e-09],
         [ 8.56376459e-08, -2.25709839e-08, -9.46631729e-09],
         [ 6.36663061e-08, -6.34963091e-09,  1.06478958e-07],
         [ 6.91991838e-08,  3.68037262e-08,  7.60792496e-09],
         [ 1.26307789e-08, -8.82248409e-09,  4.39922183e-09]],

        [[ 6.91087263e-08,  2.73337378e-08,  5.05160975e-08],
  

In [13]:
y-(a*X+b)

array([[[[ 5.36777740e-08, -3.73838105e-09,  1.89161249e-08],
         [ 1.20542423e-07, -3.27244243e-08,  4.79527544e-08],
         [ 2.88789683e-08, -9.40033917e-09,  6.22456520e-08],
         [ 2.09851699e-08, -6.51879245e-09,  4.85770374e-08],
         [ 1.18457949e-07, -3.14339626e-08,  3.11368208e-08]],

        [[ 1.30206489e-08,  3.14202093e-08, -1.45432528e-08],
         [ 1.08402885e-07, -3.17526684e-08,  1.45676107e-08],
         [ 5.24706034e-09,  7.33863832e-08, -5.01572121e-09],
         [ 1.66940604e-07, -3.21565670e-08,  1.37810944e-08],
         [ 9.46704559e-09, -2.68650756e-08,  2.13263515e-08]],

        [[ 3.70833362e-08, -2.84249047e-08, -7.63447205e-09],
         [ 1.27865133e-07, -3.49552840e-08,  1.77123056e-08],
         [ 1.06273679e-07, -2.47546781e-08,  1.30940450e-07],
         [ 9.65109479e-08, -7.98707711e-09,  5.90839200e-09],
         [ 2.75917844e-08, -2.39666569e-08,  3.51320256e-09]],

        [[ 1.16169230e-07, -1.43856096e-08,  7.22153582e-08],
  

In [14]:
a
b

array([-0.1641582 , -0.16172302, -0.21955355], dtype=float32)

In [15]:
in_json = {
    "in": (X[0]*1000).round().astype(int).astype(str).tolist(),
    "a": (a*1000).round().astype(int).astype(str).tolist(),
    "b": (b*1000*1000).round().astype(int).astype(str).tolist()
}

In [16]:
out_json = {
    "out": (y*1000000).round().astype(int).flatten().tolist()
}

In [17]:
import json

In [18]:
with open("batchNormalization_input.json", "w") as f:
    json.dump(in_json, f)

In [19]:
with open("batchNormalization_output.json", "w") as f:
    json.dump(out_json, f)

In [20]:
X.shape

(1, 5, 5, 3)

In [21]:
a.shape

(3,)

In [22]:
b.shape

(3,)