In [1]:
from tensorflow.keras.layers import Input, Conv1D
from tensorflow.keras import Model
import numpy as np

In [2]:
inputs = Input(shape=(20,3))
x = Conv1D(2,4,3)(inputs)
model = Model(inputs, x)

In [3]:
model.summary()

Model: "functional"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ input_layer (InputLayer)        │ (None, 20, 3)          │             0 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ conv1d (Conv1D)                 │ (None, 6, 2)           │            26 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 26 (104.00 B)

 Trainable params: 26 (104.00 B)

 Non-trainable params: 0 (0.00 B)

In [4]:
model.weights

[<Variable path=conv1d/kernel, shape=(4, 3, 2), dtype=float32, value=[[[-0.17290235 -0.37409627]
   [-0.1487911  -0.26304552]
   [-0.52389497  0.19885916]]
 
  [[-0.265338    0.43149263]
   [ 0.13004673  0.49418712]
   [ 0.01650703 -0.525739  ]]
 
  [[ 0.02907175 -0.40906113]
   [-0.01426429  0.22336894]
   [-0.22779402 -0.03654313]]
 
  [[ 0.1735686  -0.0106439 ]
   [-0.01128441  0.5406997 ]
   [-0.49673453 -0.27933186]]]>,
 <Variable path=conv1d/bias, shape=(2,), dtype=float32, value=[0. 0.]>]

In [31]:
X = np.random.rand(1,20,3)
X

array([[[0.53543076, 0.55713139, 0.32876356],
        [0.91660228, 0.47852859, 0.20204562],
        [0.11484549, 0.63503852, 0.68284003],
        [0.71308125, 0.11350927, 0.26812584],
        [0.02969731, 0.10855637, 0.45308874],
        [0.43505321, 0.3480955 , 0.25292266],
        [0.02536507, 0.8813598 , 0.682113  ],
        [0.85441284, 0.37160591, 0.75305606],
        [0.66242421, 0.25225665, 0.62480121],
        [0.50937159, 0.08178985, 0.70072047],
        [0.47194453, 0.84449063, 0.81184201],
        [0.04595213, 0.25674389, 0.23592202],
        [0.49285079, 0.3338343 , 0.87336952],
        [0.73993546, 0.47228246, 0.64377546],
        [0.85940834, 0.38943075, 0.58044022],
        [0.86389687, 0.64740411, 0.69472046],
        [0.40508285, 0.1547064 , 0.62286387],
        [0.21864135, 0.4158502 , 0.56989528],
        [0.76123006, 0.47144711, 0.59453934],
        [0.35446747, 0.68615368, 0.29709978]]])

In [32]:
y = model.predict(X)
y

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 17ms/step


array([[[-0.6973204 ,  0.29309487],
        [-0.6612396 , -0.23875211],
        [-1.0460817 , -0.34366694],
        [-0.87747   ,  0.08266455],
        [-1.031971  , -0.02327147],
        [-0.9846583 , -0.3681858 ]]], dtype=float32)

In [33]:
# Unwrap X and y out of their containing single-element arrays for circom consumption
X = X[0]
y = y[0]

In [34]:
in_json = {
    "in": (X*1000).round().astype(int).astype(str).tolist(),
    "weights": (model.weights[0].numpy()*1000).round().astype(int).astype(str).tolist(),
    "bias": np.zeros(model.weights[1].numpy().shape).astype(int).astype(str).tolist()
}
in_json

{'in': [['535', '557', '329'],
  ['917', '479', '202'],
  ['115', '635', '683'],
  ['713', '114', '268'],
  ['30', '109', '453'],
  ['435', '348', '253'],
  ['25', '881', '682'],
  ['854', '372', '753'],
  ['662', '252', '625'],
  ['509', '82', '701'],
  ['472', '844', '812'],
  ['46', '257', '236'],
  ['493', '334', '873'],
  ['740', '472', '644'],
  ['859', '389', '580'],
  ['864', '647', '695'],
  ['405', '155', '623'],
  ['219', '416', '570'],
  ['761', '471', '595'],
  ['354', '686', '297']],
 'weights': [[['-173', '-374'], ['-149', '-263'], ['-524', '199']],
  [['-265', '431'], ['130', '494'], ['17', '-526']],
  [['29', '-409'], ['-14', '223'], ['-228', '-37']],
  [['174', '-11'], ['-11', '541'], ['-497', '-279']]],
 'bias': ['0', '0']}

In [35]:
out_json = {
    "out": (y*1000000).round().astype(int).astype(str).tolist()
}
out_json

{'out': [['-697320', '293095'],
  ['-661240', '-238752'],
  ['-1046082', '-343667'],
  ['-877470', '82665'],
  ['-1031971', '-23271'],
  ['-984658', '-368186']]}

In [36]:
in_flat_json = {
    "in": (X*1000).round().astype(int).flatten().tolist(),
    "weights": (model.weights[0].numpy()*1000).round().astype(int).flatten().tolist(),
    "bias": np.zeros(model.weights[1].numpy().shape).tolist()
}
in_flat_json

{'in': [535,
  557,
  329,
  917,
  479,
  202,
  115,
  635,
  683,
  713,
  114,
  268,
  30,
  109,
  453,
  435,
  348,
  253,
  25,
  881,
  682,
  854,
  372,
  753,
  662,
  252,
  625,
  509,
  82,
  701,
  472,
  844,
  812,
  46,
  257,
  236,
  493,
  334,
  873,
  740,
  472,
  644,
  859,
  389,
  580,
  864,
  647,
  695,
  405,
  155,
  623,
  219,
  416,
  570,
  761,
  471,
  595,
  354,
  686,
  297],
 'weights': [-173,
  -374,
  -149,
  -263,
  -524,
  199,
  -265,
  431,
  130,
  494,
  17,
  -526,
  29,
  -409,
  -14,
  223,
  -228,
  -37,
  174,
  -11,
  -11,
  541,
  -497,
  -279],
 'bias': [0.0, 0.0]}

In [37]:
out_flat_json = {
    "out": (y*1000000).round().astype(int).flatten().tolist()
}
out_flat_json

{'out': [-697320,
  293095,
  -661240,
  -238752,
  -1046082,
  -343667,
  -877470,
  82665,
  -1031971,
  -23271,
  -984658,
  -368186]}

In [38]:
import json

In [39]:
with open("conv1D_input.json", "w") as f:
    json.dump(in_json, f, indent=4)

In [40]:
with open("conv1D_output.json", "w") as f:
    json.dump(out_json, f, indent=4)

In [41]:
with open("conv1D_input_flatten.json", "w") as f:
    json.dump(in_flat_json, f, indent=4)

In [42]:
with open("conv1D_output_flattened.json", "w") as f:
    json.dump(out_flat_json, f, indent=4)