In [1]:
from tensorflow.keras.layers import Input, Conv2D
from tensorflow.keras import Model
import numpy as np

In [2]:
inputs = Input(shape=(5,5,3))
x = Conv2D(2, 3)(inputs)
model = Model(inputs, x)

In [3]:
model.summary()

Model: "functional"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ input_layer (InputLayer)        │ (None, 5, 5, 3)        │             0 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ conv2d (Conv2D)                 │ (None, 3, 3, 2)        │            56 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 56 (224.00 B)

 Trainable params: 56 (224.00 B)

 Non-trainable params: 0 (0.00 B)

In [4]:
model.weights

[<Variable path=conv2d/kernel, shape=(3, 3, 3, 2), dtype=float32, value=[[[[ 0.18426293  0.31137365]
    [-0.07373163 -0.04408792]
    [-0.11678302 -0.21504723]]
 
   [[ 0.19148952  0.11537531]
    [-0.07348067  0.10527524]
    [-0.23091453 -0.16828237]]
 
   [[ 0.322573   -0.23062062]
    [ 0.14879233 -0.20433097]
    [ 0.2765969  -0.00831848]]]
 
 
  [[[-0.28654373 -0.23623422]
    [-0.20444363 -0.35005945]
    [ 0.3076164   0.07403156]]
 
   [[-0.21774715  0.17493701]
    [-0.26682124  0.03182897]
    [ 0.1706186   0.24310946]]
 
   [[-0.08349225 -0.21714863]
    [ 0.1794684  -0.34100646]
    [-0.09891444 -0.3211692 ]]]
 
 
  [[[ 0.22669917  0.00725254]
    [-0.10420468  0.17496175]
    [ 0.1679579   0.22802192]]
 
   [[-0.31850773 -0.23770393]
    [ 0.05354965  0.06220496]
    [-0.31127626 -0.0337427 ]]
 
   [[ 0.1431467  -0.26823306]
    [-0.17588115 -0.32343054]
    [ 0.12632373 -0.0630773 ]]]]>,
 <Variable path=conv2d/bias, shape=(2,), dtype=float32, value=[0. 0.]>]

In [5]:
X = np.random.rand(1,5,5,3)
X

array([[[[0.60667804, 0.3990403 , 0.72384216],
         [0.89256566, 0.62458507, 0.55978954],
         [0.98062863, 0.20523633, 0.21440016],
         [0.72406067, 0.76287269, 0.09254982],
         [0.4489614 , 0.86270877, 0.86792637]],

        [[0.36624968, 0.36707174, 0.00766375],
         [0.48163207, 0.05188973, 0.7428503 ],
         [0.65653268, 0.8684728 , 0.92758775],
         [0.90641156, 0.51814291, 0.60780973],
         [0.10562948, 0.66789842, 0.63206341]],

        [[0.28339569, 0.07334104, 0.25280184],
         [0.66536663, 0.66110638, 0.13433204],
         [0.43229978, 0.07172454, 0.45507118],
         [0.90055775, 0.21398729, 0.20751309],
         [0.2989524 , 0.97205557, 0.54315467]],

        [[0.62632015, 0.01132305, 0.20508215],
         [0.61940887, 0.47657714, 0.33695395],
         [0.81380474, 0.95563708, 0.45537253],
         [0.74499849, 0.16725261, 0.15770063],
         [0.96373176, 0.63185112, 0.29357592]],

        [[0.47835664, 0.28604489, 0.00555507],
     

In [6]:
y = model.predict(X)
y

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 62ms/step


array([[[[ 0.22692308, -1.0811708 ],
         [ 0.3160648 , -0.65902275],
         [ 0.21870358, -0.92703825]],

        [[ 0.07348766, -1.104415  ],
         [-0.09922928, -1.0947828 ],
         [ 0.07934897, -0.96861917]],

        [[-0.09620575, -1.0236564 ],
         [-0.20732252, -0.71761304],
         [-0.17671457, -1.3056287 ]]]], dtype=float32)

In [7]:
in_json = {
    "in": (X[0]*1000).round().astype(int).astype(str).tolist(),
    "weights": (model.weights[0].numpy()*1000).round().astype(int).astype(str).tolist(),
    "bias": ["0","0"]
}

In [8]:
out_json = {
    "out": (y*1000000).round().astype(int).flatten().tolist()
}

In [9]:
import json

In [10]:
with open("conv2D_input.json", "w") as f:
    json.dump(in_json, f)

In [11]:
with open("conv2D_output.json", "w") as f:
    json.dump(out_json, f)

In [12]:
inputs = Input(shape=(10,10,3))
x = Conv2D(2, 4, 3)(inputs)
model = Model(inputs, x)

In [13]:
model.summary()

Model: "functional_1"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ input_layer_1 (InputLayer)      │ (None, 10, 10, 3)      │             0 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ conv2d_1 (Conv2D)               │ (None, 3, 3, 2)        │            98 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 98 (392.00 B)

 Trainable params: 98 (392.00 B)

 Non-trainable params: 0 (0.00 B)

In [14]:
model.weights

[<Variable path=conv2d_1/kernel, shape=(4, 4, 3, 2), dtype=float32, value=[[[[ 9.43866968e-02 -1.07372940e-01]
    [ 2.10932195e-02  8.41921568e-03]
    [-1.07936949e-01  5.33478856e-02]]
 
   [[ 6.03355467e-02  1.97409302e-01]
    [-2.45161936e-01  2.13089973e-01]
    [ 3.39010358e-02  2.54302502e-01]]
 
   [[-2.39671722e-01 -3.05446237e-02]
    [ 1.37694448e-01  2.23471910e-01]
    [-4.69222218e-02 -3.79400998e-02]]
 
   [[ 1.49527937e-01 -2.18599260e-01]
    [ 6.23013377e-02 -2.00787932e-01]
    [ 1.27245367e-01  2.02018529e-01]]]
 
 
  [[[ 1.77735835e-01 -2.27464169e-01]
    [ 2.25489289e-01  9.20081735e-02]
    [-2.12191015e-01  1.31348878e-01]]
 
   [[ 2.16174960e-01 -2.30238825e-01]
    [-1.66951925e-01 -2.71104455e-01]
    [ 1.77460611e-01  8.10297728e-02]]
 
   [[ 8.93524885e-02 -1.78350762e-01]
    [-1.91546276e-01  9.91217792e-02]
    [ 2.37208784e-01 -1.04716346e-01]]
 
   [[-2.43753821e-01 -2.28295222e-01]
    [ 9.61746871e-02 -6.74637854e-02]
    [ 7.08782673e-03  1.15743

In [15]:
X = np.random.rand(1,10,10,3)
X

array([[[[0.11365527, 0.58099601, 0.85495219],
         [0.06488493, 0.96507641, 0.57181432],
         [0.39861892, 0.05675521, 0.07317276],
         [0.57371779, 0.02983131, 0.09611564],
         [0.61840017, 0.11565882, 0.60493761],
         [0.60224167, 0.80283956, 0.90436352],
         [0.32839054, 0.22592251, 0.18376245],
         [0.95922491, 0.88882158, 0.73302537],
         [0.58426787, 0.80243882, 0.97578109],
         [0.78470373, 0.6142635 , 0.64809618]],

        [[0.34712083, 0.51390976, 0.54399463],
         [0.1910795 , 0.33802964, 0.99730721],
         [0.32423329, 0.05922151, 0.23581999],
         [0.30256769, 0.53627661, 0.37337376],
         [0.29276445, 0.01078959, 0.48208627],
         [0.53672934, 0.83276761, 0.03566746],
         [0.25817637, 0.84437052, 0.42258149],
         [0.77390395, 0.31932508, 0.68565645],
         [0.90872645, 0.5767924 , 0.18020372],
         [0.88234072, 0.2634728 , 0.46533755]],

        [[0.73949634, 0.55322277, 0.26621991],
         

In [16]:
y = model.predict(X)
y

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 22ms/step


array([[[[ 0.41676652,  0.3145341 ],
         [ 0.4813154 ,  0.56148064],
         [ 0.49797642,  0.50393534]],

        [[ 0.32347542, -0.1454651 ],
         [ 0.03534333,  0.31049258],
         [ 0.36492527, -0.20417881]],

        [[-0.49467736,  0.2991291 ],
         [ 0.40228626,  0.49291104],
         [ 0.32195124,  0.42111522]]]], dtype=float32)

In [17]:
in_json = {
    "in": (X[0]*1000).round().astype(int).astype(str).tolist(),
    "weights": (model.weights[0].numpy()*1000).round().astype(int).astype(str).tolist(),
    "bias": ["0","0"]
}

In [18]:
out_json = {
    "out": (y*1000000).round().astype(int).flatten().tolist()
}

In [19]:
with open("conv2D_stride_input.json", "w") as f:
    json.dump(in_json, f)

In [20]:
with open("conv2D_stride_output.json", "w") as f:
    json.dump(out_json, f)