In [1]:
from tensorflow.keras.layers import Input, MaxPooling2D
from tensorflow.keras import Model
import numpy as np

In [2]:
inputs = Input(shape=(5,5,3))
x = MaxPooling2D(pool_size=2)(inputs)
model = Model(inputs, x)

In [3]:
model.summary()

Model: "functional"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ input_layer (InputLayer)        │ (None, 5, 5, 3)        │             0 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ max_pooling2d (MaxPooling2D)    │ (None, 2, 2, 3)        │             0 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 0 (0.00 B)

 Trainable params: 0 (0.00 B)

 Non-trainable params: 0 (0.00 B)

In [4]:
X = np.random.rand(1,5,5,3)
X

array([[[[0.13321753, 0.97445949, 0.33146142],
         [0.60294649, 0.61122533, 0.53512476],
         [0.47907312, 0.69359879, 0.32999213],
         [0.54536165, 0.78870848, 0.4172727 ],
         [0.72331264, 0.42963276, 0.49728672]],

        [[0.19436892, 0.76772636, 0.49445903],
         [0.76657489, 0.95922142, 0.82639391],
         [0.4623748 , 0.38687326, 0.19470174],
         [0.2911568 , 0.18411622, 0.75451513],
         [0.551599  , 0.9332176 , 0.74311063]],

        [[0.32181014, 0.88144079, 0.37834975],
         [0.74970165, 0.37230795, 0.37070961],
         [0.01677686, 0.79069027, 0.08021334],
         [0.28574113, 0.685475  , 0.08186891],
         [0.53255199, 0.22637009, 0.83859894]],

        [[0.61161142, 0.97869771, 0.37552024],
         [0.12262857, 0.03362508, 0.14552388],
         [0.77164048, 0.6711948 , 0.00263185],
         [0.98245964, 0.56975591, 0.50138517],
         [0.69547234, 0.3120787 , 0.57266111]],

        [[0.4188474 , 0.04654456, 0.50353378],
     

In [5]:
y = model.predict(X)
y

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 33ms/step


array([[[[0.7665749 , 0.97445947, 0.8263939 ],
         [0.54536164, 0.7887085 , 0.7545151 ]],

        [[0.7497016 , 0.9786977 , 0.37834975],
         [0.98245966, 0.79069024, 0.50138515]]]], dtype=float32)

In [6]:
in_json = {
    "in": (X[0]*1000).round().astype(int).astype(str).tolist()
}

In [7]:
out_json = {
    "out": (y*1000).round().astype(int).flatten().tolist()
}

In [8]:
import json

In [9]:
with open("maxPooling2D_input.json", "w") as f:
    json.dump(in_json, f)

In [10]:
with open("maxPooling2D_output.json", "w") as f:
    json.dump(out_json, f)

In [11]:
inputs = Input(shape=(10,10,3))
x = MaxPooling2D(pool_size=2, strides=3)(inputs)
model = Model(inputs, x)

In [12]:
model.summary()

Model: "functional_1"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ input_layer_1 (InputLayer)      │ (None, 10, 10, 3)      │             0 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ max_pooling2d_1 (MaxPooling2D)  │ (None, 3, 3, 3)        │             0 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 0 (0.00 B)

 Trainable params: 0 (0.00 B)

 Non-trainable params: 0 (0.00 B)

In [13]:
X = np.random.rand(1,10,10,3)
X

array([[[[0.51672287, 0.73043554, 0.38435166],
         [0.54077712, 0.52259286, 0.48995291],
         [0.51015617, 0.90840683, 0.14396171],
         [0.33097806, 0.6057087 , 0.3560294 ],
         [0.19378428, 0.75788202, 0.55044338],
         [0.63740637, 0.52837049, 0.19463607],
         [0.60984031, 0.13459982, 0.05764127],
         [0.21393059, 0.45116761, 0.49648125],
         [0.21199046, 0.91815598, 0.71984819],
         [0.35010238, 0.9426379 , 0.60981232]],

        [[0.34035698, 0.85418841, 0.14261173],
         [0.33252601, 0.75466495, 0.40072395],
         [0.87846621, 0.45469272, 0.49237839],
         [0.93640143, 0.30651093, 0.12365961],
         [0.99214004, 0.21715434, 0.92840197],
         [0.52937847, 0.60851693, 0.97721032],
         [0.17772131, 0.35071231, 0.53629307],
         [0.40565698, 0.10065592, 0.94476663],
         [0.8820701 , 0.52317832, 0.00902416],
         [0.61591273, 0.13106379, 0.12313185]],

        [[0.08665206, 0.98374697, 0.01302586],
         

In [14]:
y = model.predict(X)
y

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 19ms/step


array([[[[0.54077715, 0.8541884 , 0.48995292],
         [0.99214005, 0.757882  , 0.92840195],
         [0.60984033, 0.4511676 , 0.94476664]],

        [[0.9156339 , 0.79738194, 0.55285764],
         [0.9706159 , 0.8144351 , 0.29502314],
         [0.8130237 , 0.773373  , 0.99218345]],

        [[0.8043834 , 0.98170334, 0.9935605 ],
         [0.3778529 , 0.91671455, 0.9064955 ],
         [0.9916203 , 0.8563385 , 0.20240228]]]], dtype=float32)

In [15]:
in_json = {
    "in": (X[0]*1000).round().astype(int).astype(str).tolist()
}

In [16]:
out_json = {
    "out": (y*1000).round().astype(int).flatten().tolist()
}

In [17]:
with open("maxPooling2D_stride_input.json", "w") as f:
    json.dump(in_json, f)

In [18]:
with open("maxPooling2D_stride_output.json", "w") as f:
    json.dump(out_json, f)