In [1]:
from tensorflow.keras.layers import Input, Conv2D, AveragePooling2D, Flatten, Softmax, Dense, Lambda, BatchNormalization, ReLU
from tensorflow.keras import Model
from tensorflow.keras.datasets import mnist
from tensorflow.keras.utils import to_categorical
from tensorflow.keras.optimizers import SGD
import numpy as np
import matplotlib.pyplot as plt
import tensorflow as tf

In [2]:
(X_train, y_train), (X_test, y_test) = mnist.load_data()

In [3]:
# Convert y_train into one-hot format
temp = []
for i in range(len(y_train)):
    temp.append(to_categorical(y_train[i], num_classes=10))
y_train = np.array(temp)
# Convert y_test into one-hot format
temp = []
for i in range(len(y_test)):    
    temp.append(to_categorical(y_test[i], num_classes=10))
y_test = np.array(temp)

In [4]:
#reshaping
X_train = X_train.reshape(X_train.shape[0], 28, 28, 1)
X_test = X_test.reshape(X_test.shape[0], 28, 28, 1)

In [5]:
inputs = Input(shape=(28,28,1))
out = Lambda(lambda x: x/1000)(inputs)
out = Conv2D(4, 3, use_bias=False)(out)
out = BatchNormalization()(out)
out = ReLU()(out)
# out = Lambda(lambda x: x**2+x)(out)
out = AveragePooling2D(1)(out)
# out = Lambda(lambda x: x*4)(out)
out = Conv2D(8, 3, use_bias=False)(out)
out = BatchNormalization()(out)
out = ReLU()(out)
# out = Lambda(lambda x: x**2+x)(out)
out = AveragePooling2D(1)(out)
# out = Lambda(lambda x: x*4)(out)
out = Flatten()(out)
out = Dense(10, activation=None)(out)
out = Softmax()(out)
model = Model(inputs, out)

In [6]:
model.summary()

Model: "functional"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ input_layer (InputLayer)        │ (None, 28, 28, 1)      │             0 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ lambda (Lambda)                 │ (None, 28, 28, 1)      │             0 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ conv2d (Conv2D)                 │ (None, 26, 26, 4)      │            36 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ batch_normalization             │ (None, 26, 26, 4)      │            16 │
│ (BatchNormalization)            │                        │               │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ re_lu (ReLU)                    │ (None, 26, 26, 4)      │             0 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ average_pooling2d               │ (None, 26, 26, 4)      │             0 │
│ (AveragePooling2D)              │                        │               │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ conv2d_1 (Conv2D)               │ (None, 24, 24, 8)      │           288 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ batch_normalization_1           │ (None, 24, 24, 8)      │            32 │
│ (BatchNormalization)            │                        │               │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ re_lu_1 (ReLU)                  │ (None, 24, 24, 8)      │             0 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ average_pooling2d_1             │ (None, 24, 24, 8)      │             0 │
│ (AveragePooling2D)              │                        │               │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ flatten (Flatten)               │ (None, 4608)           │             0 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense (Dense)                   │ (None, 10)             │        46,090 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ softmax (Softmax)               │ (None, 10)             │             0 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 46,462 (181.49 KB)

 Trainable params: 46,438 (181.40 KB)

 Non-trainable params: 24 (96.00 B)

In [7]:
model.compile(
    loss='categorical_crossentropy',
    optimizer=SGD(learning_rate=0.01, momentum=0.9),
    metrics=['acc']
    )

In [8]:
model.fit(X_train, y_train, epochs=15, batch_size=32, validation_data=(X_test, y_test))

Epoch 1/15
1875/1875 ━━━━━━━━━━━━━━━━━━━━ 8s 4ms/step - acc: 0.9579 - loss: 0.1413 - val_acc: 0.9766 - val_loss: 0.0811
Epoch 2/15
1875/1875 ━━━━━━━━━━━━━━━━━━━━ 8s 4ms/step - acc: 0.9794 - loss: 0.0674 - val_acc: 0.9817 - val_loss: 0.0588
Epoch 3/15
1875/1875 ━━━━━━━━━━━━━━━━━━━━ 8s 4ms/step - acc: 0.9842 - loss: 0.0513 - val_acc: 0.9822 - val_loss: 0.0572
Epoch 4/15
1875/1875 ━━━━━━━━━━━━━━━━━━━━ 8s 4ms/step - acc: 0.9868 - loss: 0.0423 - val_acc: 0.9830 - val_loss: 0.0530
Epoch 5/15
1875/1875 ━━━━━━━━━━━━━━━━━━━━ 8s 4ms/step - acc: 0.9887 - loss: 0.0352 - val_acc: 0.9816 - val_loss: 0.0601
Epoch 6/15
1875/1875 ━━━━━━━━━━━━━━━━━━━━ 8s 4ms/step - acc: 0.9909 - loss: 0.0285 - val_acc: 0.9823 - val_loss: 0.0584
Epoch 7/15
1875/1875 ━━━━━━━━━━━━━━━━━━━━ 8s 4ms/step - acc: 0.9920 - loss: 0.0245 - val_acc: 0.9840 - val_loss: 0.0603
Epoch 8/15
1875/1875 ━━━━━━━━━━━━━━━━━━━━ 8s 4ms/step - acc: 0.9937 - loss: 0.0191 - val_acc: 0.9799 - val_loss: 0.0763
Epoch 9/15
1875/1875 ━━━━━━━━━━━━━━━━━━━

In [9]:
X = X_test[0]
X.shape, X.min(), X.max()

((28, 28, 1), np.uint8(0), np.uint8(255))

In [10]:
model2 = Model(model.input, model.layers[-2].output)

In [11]:
y = model2.predict(X_test[[0]]) - model.layers[-2].weights[1].numpy()

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 36ms/step


In [12]:
print(len(model.weights))
for weights in model.weights:
    print(weights.shape)

12
(3, 3, 1, 4)
(4,)
(4,)
(4,)
(4,)
(3, 3, 4, 8)
(8,)
(8,)
(8,)
(8,)
(4608, 10)
(10,)


In [13]:
gamma = model.layers[3].weights[0].numpy()
beta = model.layers[3].weights[1].numpy()
moving_mean = model.layers[3].weights[2].numpy()
moving_var = model.layers[3].weights[3].numpy()
epsilon = model.layers[3].epsilon

In [14]:
a1 = gamma/(moving_var+epsilon)**.5
b1 = beta-gamma*moving_mean/(moving_var+epsilon)**.5
a1, b1

(array([ 6.956524, 10.364138, 10.012734,  8.431484], dtype=float32),
 array([ 0.7954873 , -0.0376676 , -0.27488744, -0.12941366], dtype=float32))

In [15]:
gamma = model.layers[7].weights[0].numpy()
beta = model.layers[7].weights[1].numpy()
moving_mean = model.layers[7].weights[2].numpy()
moving_var = model.layers[7].weights[3].numpy()
epsilon = model.layers[7].epsilon

In [16]:
a2 = gamma/(moving_var+epsilon)**.5
b2 = beta-gamma*moving_mean/(moving_var+epsilon)**.5
a2, b2

(array([1.1154891, 1.003639 , 1.2166711, 1.2282268, 0.8227037, 0.80484  ,
        0.8499036, 1.1205083], dtype=float32),
 array([-1.6531496 ,  0.19064945,  1.285681  , -0.27838057, -0.23562062,
         0.4966468 , -0.536916  ,  1.0208457 ], dtype=float32))

In [28]:
in_json = {
    "in": X.astype(int).astype(str).tolist(), # X is already 1000 times to begin with
    "conv2d_1_weights": (model.layers[2].weights[0].numpy()*(10**3)).round().astype(int).astype(str).tolist(),
    "conv2d_1_bias": (np.array([0]*4)*(10**3)**2).round().astype(int).astype(str).tolist(),
    "bn_1_a": (a1*(10**3)).round().astype(int).astype(str).tolist(),
    "bn_1_b": (b1*(10**3)**3).round().astype(int).astype(str).tolist(),
    # average pooling will scale another 10**2 times
    "conv2d_2_weights": (model.layers[6].weights[0].numpy()*(10**3)).round().astype(int).astype(str).tolist(),
    "conv2d_2_bias": (np.array([0]*8)*(10**(3*4+2))).round().astype(int).astype(str).tolist(),
    "bn_2_a": (a2*(10**3)).round().astype(int).astype(str).tolist(),
    "bn_2_b": (b2*(10**(3*5+2))).round().astype(int).astype(str).tolist(),
    # average pooling will scale another 10**2 times
    "dense_weights":(model.layers[11].weights[0].numpy()*(10**3)).round().astype(int).astype(str).tolist(),
    "dense_bias": np.zeros(model.layers[11].weights[1].numpy().shape).astype(int).astype(str).tolist() # zero because we are not doing softmax in circom, just argmax
}
in_json["dense_weights"] = in_json["dense_weights"][0:200]

In [29]:
out_json = {
    "scale": 10**-22,
    "out": y.flatten().tolist(),
    "label": int(y.argmax())
}
out_json

{'scale': 1e-22,
 'out': [-5.7563910484313965,
  -0.03786469250917435,
  1.764357328414917,
  10.282814025878906,
  -10.94578742980957,
  -6.905069351196289,
  -23.06777572631836,
  33.47208023071289,
  -2.164367437362671,
  0.05366566777229309],
 'label': 7}

In [30]:
import json

In [31]:
with open("mnist_latest_precision_input.json", "w") as f:
    json.dump(in_json, f)

In [32]:
with open("mnist_latest_precision_output.json", "w") as f:
    json.dump(out_json, f)