In [5]:
from tensorflow.keras.layers import Input, Conv2D, AveragePooling2D, Flatten, Softmax, Dense, Lambda, BatchNormalization
from tensorflow.keras import Model
from tensorflow.keras.datasets import mnist
from tensorflow.keras.utils import to_categorical
from tensorflow.keras.optimizers import Adam, SGD
import numpy as np
import matplotlib.pyplot as plt
import tensorflow as tf

In [6]:
(X_train, y_train), (X_test, y_test) = mnist.load_data()

In [7]:
# Convert y_train into one-hot format
temp = []
for i in range(len(y_train)):
    temp.append(to_categorical(y_train[i], num_classes=10))
y_train = np.array(temp)
# Convert y_test into one-hot format
temp = []
for i in range(len(y_test)):    
    temp.append(to_categorical(y_test[i], num_classes=10))
y_test = np.array(temp)

In [8]:
#reshaping
X_train = X_train.reshape(X_train.shape[0], 28, 28, 1)
X_test = X_test.reshape(X_test.shape[0], 28, 28, 1)

In [9]:
inputs = Input(shape=(28,28,1))
out = Lambda(lambda x: x/100)(inputs)
out = Conv2D(4, 3, use_bias=False)(out)
out = BatchNormalization()(out)
out = Lambda(lambda x: x**2+x)(out)
out = AveragePooling2D(1)(out)
# out = Lambda(lambda x: x*4)(out)
out = Conv2D(8, 3, use_bias=False)(out)
out = BatchNormalization()(out)
out = Lambda(lambda x: x**2+x)(out)
out = AveragePooling2D(1)(out)
# out = Lambda(lambda x: x*4)(out)
out = Flatten()(out)
out = Dense(10, activation=None)(out)
out = Softmax()(out)
model = Model(inputs, out)

In [10]:
model.summary()

Model: "functional"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ input_layer (InputLayer)        │ (None, 28, 28, 1)      │             0 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ lambda (Lambda)                 │ (None, 28, 28, 1)      │             0 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ conv2d (Conv2D)                 │ (None, 26, 26, 4)      │            36 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ batch_normalization             │ (None, 26, 26, 4)      │            16 │
│ (BatchNormalization)            │                        │               │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ lambda_1 (Lambda)               │ (None, 26, 26, 4)      │             0 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ average_pooling2d               │ (None, 26, 26, 4)      │             0 │
│ (AveragePooling2D)              │                        │               │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ conv2d_1 (Conv2D)               │ (None, 24, 24, 8)      │           288 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ batch_normalization_1           │ (None, 24, 24, 8)      │            32 │
│ (BatchNormalization)            │                        │               │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ lambda_2 (Lambda)               │ (None, 24, 24, 8)      │             0 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ average_pooling2d_1             │ (None, 24, 24, 8)      │             0 │
│ (AveragePooling2D)              │                        │               │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ flatten (Flatten)               │ (None, 4608)           │             0 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense (Dense)                   │ (None, 10)             │        46,090 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ softmax (Softmax)               │ (None, 10)             │             0 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 46,462 (181.49 KB)

 Trainable params: 46,438 (181.40 KB)

 Non-trainable params: 24 (96.00 B)

In [11]:
model.compile(
    loss='categorical_crossentropy',
    optimizer=SGD(learning_rate=0.01, momentum=0.9),
    metrics=['acc']
    )

In [12]:
model.fit(X_train, y_train, epochs=15, batch_size=32, validation_data=(X_test, y_test))

Epoch 1/15
1875/1875 ━━━━━━━━━━━━━━━━━━━━ 8s 4ms/step - acc: 0.9464 - loss: 0.2163 - val_acc: 0.9721 - val_loss: 0.0851
Epoch 2/15
1875/1875 ━━━━━━━━━━━━━━━━━━━━ 8s 4ms/step - acc: 0.9755 - loss: 0.0805 - val_acc: 0.9685 - val_loss: 0.1018
Epoch 3/15
1875/1875 ━━━━━━━━━━━━━━━━━━━━ 8s 4ms/step - acc: 0.9809 - loss: 0.0619 - val_acc: 0.9755 - val_loss: 0.0969
Epoch 4/15
1875/1875 ━━━━━━━━━━━━━━━━━━━━ 8s 4ms/step - acc: 0.9837 - loss: 0.0523 - val_acc: 0.9760 - val_loss: 0.0851
Epoch 5/15
1875/1875 ━━━━━━━━━━━━━━━━━━━━ 8s 4ms/step - acc: 0.9858 - loss: 0.0458 - val_acc: 0.9790 - val_loss: 0.0782
Epoch 6/15
1875/1875 ━━━━━━━━━━━━━━━━━━━━ 8s 4ms/step - acc: 0.9859 - loss: 0.0416 - val_acc: 0.9781 - val_loss: 0.0670
Epoch 7/15
1875/1875 ━━━━━━━━━━━━━━━━━━━━ 8s 4ms/step - acc: 0.9884 - loss: 0.0359 - val_acc: 0.9777 - val_loss: 0.0740
Epoch 8/15
1875/1875 ━━━━━━━━━━━━━━━━━━━━ 8s 4ms/step - acc: 0.9886 - loss: 0.0344 - val_acc: 0.9797 - val_loss: 0.0725
Epoch 9/15
1875/1875 ━━━━━━━━━━━━━━━━━━━

In [13]:
X = X_test[0]
X.shape, X.min(), X.max()

((28, 28, 1), np.uint8(0), np.uint8(255))

In [14]:
model2 = Model(model.input, model.layers[-2].output)

In [15]:
y = model2.predict(X_test[[0]]) - model.layers[-2].weights[1].numpy()
y

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 48ms/step


array([[ -4.275792 ,  -4.366511 ,   7.3959584,  14.9362135, -12.714705 ,
        -11.20801  , -26.313929 ,  29.341776 ,   1.2205346,   4.8439474]],
      dtype=float32)

In [16]:
print(len(model.weights))
for weights in model.weights:
    print(weights.shape)

12
(3, 3, 1, 4)
(4,)
(4,)
(4,)
(4,)
(3, 3, 4, 8)
(8,)
(8,)
(8,)
(8,)
(4608, 10)
(10,)


In [17]:
gamma = model.layers[3].weights[0].numpy()
beta = model.layers[3].weights[1].numpy()
moving_mean = model.layers[3].weights[2].numpy()
moving_var = model.layers[3].weights[3].numpy()
epsilon = model.layers[3].epsilon

In [18]:
a1 = gamma/(moving_var+epsilon)**.5
b1 = beta-gamma*moving_mean/(moving_var+epsilon)**.5
a1, b1

(array([0.7383806 , 0.634639  , 1.1350192 , 0.34767404], dtype=float32),
 array([ 2.3714292 , -0.02658033,  0.27596176,  1.4433999 ], dtype=float32))

In [19]:
gamma = model.layers[7].weights[0].numpy()
beta = model.layers[7].weights[1].numpy()
moving_mean = model.layers[7].weights[2].numpy()
moving_var = model.layers[7].weights[3].numpy()
epsilon = model.layers[7].epsilon

In [20]:
a2 = gamma/(moving_var+epsilon)**.5
b2 = beta-gamma*moving_mean/(moving_var+epsilon)**.5
a2, b2

(array([ 0.05755045,  0.04222513, -0.02407582, -0.05750043,  0.01695909,
        -0.05484693,  0.05063115,  0.066995  ], dtype=float32),
 array([-0.9004557 , -0.8276618 , -0.57591933, -0.7760942 ,  0.34479854,
         0.01766279, -0.60435754,  0.87965655], dtype=float32))

In [21]:
in_json = {
    "in": X.astype(int).astype(str).tolist(), # X is already 100 times to begin with
    "conv2d_1_weights": (model.layers[2].weights[0].numpy()*(10**2)).round().astype(int).astype(str).tolist(),
    "conv2d_1_bias": (np.array([0]*4)*(10**2)**2).round().astype(int).astype(str).tolist(),
    "bn_1_a": (a1*(10**2)).round().astype(int).astype(str).tolist(),
    "bn_1_b": (b1*(10**2)**3).round().astype(int).astype(str).tolist(),
    # poly layer would be (10**2)**3=10**6 times as well
    # average pooling will scale another 10**2 times
    "conv2d_2_weights": (model.layers[6].weights[0].numpy()*(10**2)).round().astype(int).astype(str).tolist(),
    "conv2d_2_bias": (np.array([0]*8)*((10**2)**8)).round().astype(int).astype(str).tolist(),
    "bn_2_a": (a2*(10**2)).round().astype(int).astype(str).tolist(),
    "bn_2_b": (b2*(10**2)**9).round().astype(int).astype(str).tolist(),
    # poly layer would be (10**2)**9=10**18 times as well
    # average pooling will scale another 10**2 times
    "dense_weights":(model.layers[11].weights[0].numpy()*(10**2)).round().astype(int).astype(str).tolist(),
    "dense_bias": np.zeros(model.layers[11].weights[1].numpy().shape).astype(int).astype(str).tolist() # zero because we are not doing softmax in circom, just argmax
}
in_json["dense_weights"] = in_json["dense_weights"][:200]

In [22]:
out_json = {
    "scale": 10**-40,
    "out": y.flatten().tolist(),
    "label": int(y.argmax())
}
out_json

{'scale': 1e-40,
 'out': [-4.275792121887207,
  -4.36651086807251,
  7.395958423614502,
  14.936213493347168,
  -12.714705467224121,
  -11.208009719848633,
  -26.313928604125977,
  29.34177589416504,
  1.2205345630645752,
  4.843947410583496],
 'label': 7}

In [23]:
import json

In [24]:
with open("mnist_latest_input.json", "w") as f:
    json.dump(in_json, f)

In [25]:
with open("mnist_latest_output.json", "w") as f:
    json.dump(out_json, f)