In [11]:
from tensorflow.keras.layers import Input, AveragePooling2D, Lambda
from tensorflow.keras import Model
import numpy as np

In [12]:
inputs = Input(shape=(5,5,3))
x = AveragePooling2D(pool_size=2)(inputs)
x = Lambda(lambda x: x*4)(x)
model = Model(inputs, x)

In [13]:
model.summary()

Model: "functional_1"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ input_layer_1 (InputLayer)      │ (None, 5, 5, 3)        │             0 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ average_pooling2d_1             │ (None, 2, 2, 3)        │             0 │
│ (AveragePooling2D)              │                        │               │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ lambda_1 (Lambda)               │ (None, 2, 2, 3)        │             0 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 0 (0.00 B)

 Trainable params: 0 (0.00 B)

 Non-trainable params: 0 (0.00 B)

In [14]:
X = np.random.rand(1,5,5,3)
X

array([[[[7.56859981e-01, 6.07854888e-01, 5.98500542e-01],
         [3.81973283e-01, 9.30729258e-01, 1.09027524e-01],
         [6.88598062e-01, 2.12084337e-02, 4.06854131e-01],
         [6.51581328e-01, 2.82638262e-02, 8.26466355e-02],
         [2.18526921e-01, 5.79075593e-02, 3.48719182e-01]],

        [[6.04291864e-04, 1.84282171e-01, 4.14111353e-01],
         [5.84544976e-01, 9.96300010e-02, 2.83472921e-02],
         [3.66941736e-02, 6.20862787e-01, 4.71307976e-01],
         [6.77616762e-01, 4.54463159e-01, 9.18811139e-02],
         [4.50017297e-01, 1.78698714e-01, 8.52089398e-01]],

        [[3.99301214e-01, 1.11914103e-01, 5.14027146e-01],
         [8.85326924e-01, 9.80215596e-01, 4.47086143e-01],
         [2.44146918e-01, 6.32512787e-01, 4.97770705e-01],
         [5.94544988e-01, 4.65702524e-01, 4.03370737e-01],
         [2.31713158e-01, 2.23924249e-01, 9.69707765e-01]],

        [[6.58074809e-01, 4.34672494e-01, 9.18199709e-01],
         [5.81625061e-01, 2.38976405e-01, 8.712407

In [15]:
y = model.predict(X)
y

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 21ms/step


array([[[[1.7239826, 1.8224964, 1.1499866],
         [2.0544903, 1.1247982, 1.0526899]],

        [[2.524328 , 1.7657785, 2.7505536],
         [1.6691649, 1.7968476, 1.8192253]]]], dtype=float32)

In [16]:
in_json = {
    "in": (X[0]*1000).round().astype(int).astype(str).tolist()
}

In [17]:
out_json = {
    "out": (y*1000).round().astype(int).flatten().tolist()
}

In [18]:
import json

In [19]:
with open("sumPooling2D_input.json", "w") as f:
    json.dump(in_json, f)

In [20]:
with open("sumPooling2D_output.json", "w") as f:
    json.dump(out_json, f)

In [21]:
inputs = Input(shape=(10,10,3))
x = AveragePooling2D(pool_size=2, strides=3)(inputs)
x = Lambda(lambda x: x*4)(x)
model = Model(inputs, x)

In [22]:
model.summary()

Model: "functional_2"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ input_layer_2 (InputLayer)      │ (None, 10, 10, 3)      │             0 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ average_pooling2d_2             │ (None, 3, 3, 3)        │             0 │
│ (AveragePooling2D)              │                        │               │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ lambda_2 (Lambda)               │ (None, 3, 3, 3)        │             0 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 0 (0.00 B)

 Trainable params: 0 (0.00 B)

 Non-trainable params: 0 (0.00 B)

In [23]:
X = np.random.rand(1,10,10,3)
X

array([[[[2.79724263e-01, 8.58411003e-01, 9.36710306e-01],
         [6.72252443e-01, 8.49333388e-01, 3.70626959e-01],
         [4.86068126e-01, 1.64181480e-01, 7.80743693e-01],
         [7.75254647e-02, 6.77539934e-02, 3.29565285e-01],
         [2.60070148e-02, 4.88792139e-01, 7.35326948e-01],
         [8.01538479e-01, 5.71942216e-01, 8.45028042e-01],
         [3.96191742e-01, 6.19138116e-01, 7.62540093e-01],
         [3.22986501e-01, 9.97777535e-01, 7.42117572e-02],
         [3.40176735e-01, 9.43309647e-01, 5.38309897e-01],
         [5.16629559e-01, 4.11164041e-01, 1.74221614e-01]],

        [[1.63819797e-01, 8.60582426e-02, 4.22690050e-01],
         [3.99093814e-01, 6.19350925e-01, 1.59420007e-01],
         [2.07032812e-01, 2.95146497e-01, 8.15532355e-01],
         [6.06933962e-01, 4.56239245e-01, 1.13853481e-02],
         [5.74018029e-01, 6.50010394e-01, 9.82846386e-01],
         [7.02967222e-01, 7.85977961e-02, 1.60471355e-01],
         [1.33422763e-01, 6.42387947e-01, 8.89896710e-

In [24]:
y = model.predict(X)
y

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 22ms/step


array([[[[1.5148902 , 2.4131536 , 1.8894473 ],
         [1.2844844 , 1.6627958 , 2.059124  ],
         [1.1830307 , 3.0445578 , 2.5614443 ]],

        [[2.3535771 , 1.550882  , 2.1520019 ],
         [0.97868204, 3.431989  , 0.9842633 ],
         [1.0359821 , 1.5411611 , 1.7671533 ]],

        [[2.5320773 , 2.8959177 , 1.4105129 ],
         [1.111022  , 2.2096572 , 2.2765975 ],
         [2.3642147 , 2.117791  , 1.9706846 ]]]], dtype=float32)

In [25]:
in_json = {
    "in": (X[0]*1000).round().astype(int).astype(str).tolist()
}

In [26]:
out_json = {
    "out": (y*1000).round().astype(int).astype(str).tolist()
}

In [27]:
with open("sumPooling2D_stride_input.json", "w") as f:
    json.dump(in_json, f, indent=4)

In [28]:
with open("sumPooling2D_stride_output.json", "w") as f:
    json.dump(out_json, f, indent=4)